version: 2.1

executors:
  pelican-executor:
    docker:
      - image: circleci/python3.6

commands:
  install-pelican:
    steps:
      - checkout
      - run: sudo chown -R circleci.circleci /usr/local/bin
      - run: sudo chown -R circleci.circleci /usr/local/lib/python3.6/site-packages
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - restore_cache:
          key: pelican-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            sudo pip install pipenv
            pipenv install --dev
      - save_cache:
          key: pelican-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - "venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
  build-site:
    steps:
      - run:
          command: |
            pelican content -o docs -s pelicanconf.py
  commit-site:
    steps:
      - run:
          command: |
            git commit -am "circleci cd push {{ .Branch }}" docs/
            git push

jobs:
  build:
    executor: pelican-executor
    working-directory: ""
    steps:
      - install-pelican
      - add_ssh_keys
      - run:
          name: "Add Host Fingerprints"
          command: |
          echo "$known_hosts" > ~/.ssh/known_hosts
      - build-site
      - commit-site

workflows:
  commit:
    jobs:
      - build

