version: 2.1

executors:
  pelican-executor:
    docker:
      - image: circleci/python3.6
    environment:
      LOCALE: en_US.utf8

commands:
  install-pelican:
    steps:
      - checkout
      - run: sudo chown -R circleci.circleci /usr/local/bin
      - run: sudo chown -R circleci.circleci /usr/local/lib/python3.6/site-packages
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - restore_cache:
          key: pelican-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            sudo pip install pipenv
            pipenv install --dev
      - save_cache:
          key: pelican-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - "venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
  build-site:
    steps:
      - run: pipenv run pelican content -o docs -s pelicanconf.py
  commit-site:
    steps:
      - deploy:
          name: "Trigger content deployment"
          command: |
            git config credential.helper "cache --timeout=120"
            git config user.email "ericroc.how@gmail.com"
            git config user.name "DeployTron 9000"
            git commit -am "circleci content push [skip ci]"
            git push -q https://${DOCS_GITHUB_TOKEN}@github.com/ericrochow/resume.git master

jobs:
  build:
    executor: pelican-executor
    working-directory: "~/resume"
    steps:
      - install-pelican
      - build-site
      - commit-site

workflows:
  commit:
    jobs:
      - build

